name: Build MiniKeyboard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make qt5-qmake qtbase5-dev qtbase5-dev-tools

    - name: Set QT_PATH environment variable
      run: echo "QT_PATH=$(qtpaths --install-prefix)" >> $GITHUB_ENV

    - name: Display environment variables
      run: printenv

    - name: Display Makefile for debugging
      run: cat Makefile

    - name: List project files for debugging
      run: ls -R

    - name: Build with Makefile
      env:
        QT_PATH: ${{ env.QT_PATH }}
      run: make
